### ISSUE TITLE
Add support of russian versions

### ISSUE THREAD

**Issue by nikitastepan0v** [ExOptsTeam/NFSCExOpts#32]

**Comment by mirh** [comment]
I have read [here](https://github.com/ThirteenAG/WidescreenFixesPack/issues/707) that you have the 1c softclub (russian?) version. 
Can you confirm it uses starforce drm with [this tool](https://protectionid.net/)?

**Comment by Frouk3** [comment]
> I have read [here](https://github.com/ThirteenAG/WidescreenFixesPack/issues/707) that you have the 1c softclub (russian?) version. Can you confirm it uses starforce drm with [this tool](https://protectionid.net/)?

he's just ignoring he won't confirm any because he's russian and don't understand english

**Comment by nlgxzef** [comment]
It's always easier for last user to install the English version than me finding the memory addresses and doing the entire thing from zero.
