### ISSUE TITLE
1 lap

### ISSUE THREAD

**Issue by Laur1sXd** [ExOptsTeam/NFSCExOpts#37]
Hi creators of NFS Carbon Extra Options. 
Please add 1 lap function to circuits and lap knockouts which contains in NFS Carbon Battle Royale. I will really be happy if you add this to Extra Options.

**Comment by Laur1sXd** [comment]
And please make option to disable lost races that can be redone from start without losing win percentage

**Comment by Frouk3** [comment]
> And please make option to disable lost races that can be redone from start without losing win percentage

i guess its impossible

**Comment by Frouk3** [comment]
> Hi creators of NFS Carbon Extra Options. Please add 1 lap function to circuits and lap knockouts which contains in NFS Carbon Battle Royale. I will really be happy if you add this to Extra Options.

change count in ini file

**Comment by Frouk3** [comment]
btw you are asking that impossible to do and developers never add this,because you only need that thingy

**Comment by Frouk3** [comment]
if you are so smart then go compile it yourself

**Comment by nlgxzef** [comment]
The feature is not planned for now. Sorry.
