### ISSUE TITLE
No support for the collector's edition

### ISSUE THREAD

**Issue by AndersenIAA** [ExOptsTeam/NFSCExOpts#41]
It looks like the project is dead but I just want it noted that no where could I find mention of what to do if I have the collector's edition of the game, the .exe is different and that breaks exopts.

**Comment by nlgxzef** [comment]
The project is not dead. We have lot more stuff outside Extra Options. You need to use the specified exe, the "Collector's Edition" thing just checks if the "InGameC.bun" exists in the Global folder. Also, Extra Options has a feature to skip this check to force enable Collector's Edition.

Closed.
