### ISSUE TITLE
Crew logos appear as black circles

### ISSUE THREAD

**Issue by Keith94** [ExOptsTeam/NFSCExOpts#7]
![image](https://user-images.githubusercontent.com/5490615/27866915-fd4dcb02-614c-11e7-9a01-3b87e32f499d.png)

**Comment by nlgzrgn** [comment]
It's an issue with special vinyls hack. Disable it before you select a crew logo:

`[Menu]
...
ShowSpecialVinyls = 0
...
`

**Comment by Keith94** [comment]
That did the trick. 😄 Thanks.

**Comment by nlgzrgn** [comment]
You're welcome. This is Extra Options' fault, so I'll keep this issue open until we fix it in another release.
